### ISSUE TITLE
open account is broken

### ISSUE THREAD

**Issue by imperatrona** [n0madic/twitter-scraper#104]
After login with open account GetTweets response with 403 code. But it works if downgrade to May 30 version [v0.0.0-20230530143100-fb8ae789bd97](https://pkg.go.dev/github.com/n0madic/twitter-scraper@v0.0.0-20230530143100-fb8ae789bd97)

**Comment by n0madic** [comment]
Unfortunately it does not work with timeline v2... 
GetTweets works without authorization.
OpenAccount was basically added for searching without authorization

**Comment by imperatrona** [comment]
that's sad but thanks!

**Comment by ramicaza** [comment]
Curious if there's any plan to make OpenAccount work for timeline v2? I came over from the land of python just to try this library because of the awesome OpenAccount feature. 

Also, I downgraded to the May 30 version and I still get the 403 :/ Can either of you 2 confirm if the May 30 version still works?

**Comment by n0madic** [comment]
OpenAccount is an unofficial method of partial authorization with keys leaked from mobile applications, it will not work for a long time until Twitter closes it

**Comment by imperatrona** [comment]
Can confirm that Open Account is still working for me on May 30 version when fetching user tweets
